# Generated by Django 4.2.4 on 2023-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
